{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "df296067",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting data...\n",
      "Transforming data...\n",
      "Loading into MySQL...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '15-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '16-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '20-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '23-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '28-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '18-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '20-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '25-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '28-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '15-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '18-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '25-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '28-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_8044\\318072157.py:63: UserWarning: Parsing '30-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.\n",
      "  sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ETL and Report generation successful!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "import datetime\n",
    "\n",
    "# --- DATABASE CONFIGURATION ---\n",
    "# Use the password that worked for you in MySQL Workbench\n",
    "DB_URL = 'mysql+mysqlconnector://root:vaibhav123@localhost:3306/fleximart'\n",
    "\n",
    "def run_etl():\n",
    "    report_data = {}\n",
    "    try:\n",
    "        engine = create_engine(DB_URL)\n",
    "        \n",
    "        # 1. EXTRACT\n",
    "        print(\"Extracting data...\")\n",
    "        cust_df = pd.read_csv('customers_raw.csv')\n",
    "        prod_df = pd.read_csv('products_raw.csv')\n",
    "        sales_df = pd.read_csv('sales_raw.csv')\n",
    "        \n",
    "        # Normalize columns (lowercase and strip spaces)\n",
    "        for df in [cust_df, prod_df, sales_df]:\n",
    "            df.columns = df.columns.str.strip().str.lower()\n",
    "\n",
    "        # Track initial counts for the report\n",
    "        report_data['initial_counts'] = {\n",
    "            'customers': len(cust_df),\n",
    "            'products': len(prod_df),\n",
    "            'sales': len(sales_df)\n",
    "        }\n",
    "\n",
    "        # 2. TRANSFORM\n",
    "        print(\"Transforming data...\")\n",
    "        \n",
    "        # A. Remove duplicates\n",
    "        report_data['dupes'] = {}\n",
    "        for name, df in [('customers', cust_df), ('products', prod_df), ('sales', sales_df)]:\n",
    "            pre = len(df)\n",
    "            df.drop_duplicates(inplace=True)\n",
    "            report_data['dupes'][name] = pre - len(df)\n",
    "\n",
    "        # B. Handle missing values\n",
    "        email_miss = cust_df['email'].isnull().sum()\n",
    "        cust_df['email'] = cust_df['email'].fillna('no-reply@fleximart.com')\n",
    "        \n",
    "        pre_sales = len(sales_df)\n",
    "        sales_df.dropna(subset=['customer_id', 'product_id'], inplace=True)\n",
    "        dropped_sales = pre_sales - len(sales_df)\n",
    "        report_data['missing'] = {'emails': email_miss, 'sales': dropped_sales}\n",
    "\n",
    "        # C. Standardize phone formats (+91-XXXXXXXXXX)\n",
    "        cust_df['phone'] = cust_df['phone'].astype(str).str.replace(r'\\D', '', regex=True)\n",
    "        cust_df['phone'] = '+91-' + cust_df['phone'].str[-10:]\n",
    "\n",
    "        # D. Standardize category names\n",
    "        prod_df['category'] = prod_df['category'].str.strip().str.title()\n",
    "\n",
    "        # E. Convert 'transaction_date' to YYYY-MM-DD\n",
    "        # Renaming any variant to transaction_date if needed\n",
    "        if 'transaction_date' not in sales_df.columns:\n",
    "            date_col = [c for c in sales_df.columns if 'date' in c][0]\n",
    "            sales_df.rename(columns={date_col: 'transaction_date'}, inplace=True)\n",
    "            \n",
    "        sales_df['transaction_date'] = pd.to_datetime(sales_df['transaction_date'], errors='coerce').dt.strftime('%Y-%m-%d')\n",
    "        sales_df.dropna(subset=['transaction_date'], inplace=True)\n",
    "\n",
    "        # F. Add surrogate keys\n",
    "        cust_df.insert(0, 'customer_key', range(1, 1 + len(cust_df)))\n",
    "        prod_df.insert(0, 'product_key', range(1, 1 + len(prod_df)))\n",
    "        sales_df.insert(0, 'sales_key', range(1, 1 + len(sales_df)))\n",
    "\n",
    "        # 3. LOAD\n",
    "        print(\"Loading into MySQL...\")\n",
    "        cust_df.to_sql('customers', engine, if_exists='replace', index=False)\n",
    "        prod_df.to_sql('products', engine, if_exists='replace', index=False)\n",
    "        sales_df.to_sql('sales', engine, if_exists='replace', index=False)\n",
    "\n",
    "        # Generate the Quality Report file\n",
    "        with open('data_quality_report.txt', 'w') as f:\n",
    "            f.write(f\"FLEXIMART QUALITY REPORT - {datetime.date.today()}\\n\")\n",
    "            f.write(f\"Processed: Customers({len(cust_df)}), Products({len(prod_df)}), Sales({len(sales_df)})\\n\")\n",
    "            f.write(f\"Duplicates Removed: {report_data['dupes']}\\n\")\n",
    "            f.write(f\"Missing Values: {report_data['missing']}\\n\")\n",
    "\n",
    "        print(\"ETL and Report generation successful!\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error: {e}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    run_etl()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08e5c07e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
